create table Products (
                        id int generated by default as identity primary key,
                        title varchar,
                        brand varchar,
                        total_reviews int,
                        average_score double precision,
                        url varchar
);